blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostListView.as_view(), name="post_list"),
    path("tags/<slug:tag_slug>/", views.PostListView.as_view(), name="post_list_&_tag"),
    path("<slug:post>/", views.PostDetailView.as_view(), name="post_detail"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from taggit.managers import TaggableManager

class Post(models.Model):
    STATUS_CHOISES = (
        ("draft",      "Draft"),
        ("published",  "Published")
    )

    title               = models.CharField(max_length=200)
    slug                = models.SlugField(max_length=250, unique_for_date="publish")
    author              = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_posts")
    body                = models.TextField()
    publish             = models.DateTimeField(default=timezone.now)
    created             = models.DateTimeField(auto_now_add=True)
    updated             = models.DateTimeField(auto_now=True)
    status              = models.CharField(max_length=10, default="draft", choices=STATUS_CHOISES)
    tags                = TaggableManager()

    class Meta:
        ordering = ("-publish", )
    
    def __str__(self):
        return self.title


class Comment(models.Model):
    post                = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name                = models.CharField(max_length=80)
    body                = models.TextField()
    created             = models.DateTimeField(auto_now_add=True)
    updated             = models.DateTimeField(auto_now=True)
    active              = models.BooleanField(default=True)

    class Meta:
        ordering = ("created", )
    
    def __str__(self):
        return f"comment by '{self.name}' on '{self.post}'"

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "body"]

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from .models import Post
from .forms import CommentForm

from taggit.models import Tag

class PostListView(View):
    """
        Handles everything that's related to something list of blog posts.
    """
    def get(self, request, tag_slug=None):
        post_objects = Post.objects.filter(status="published")

        tag = None
        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            post_objects = post_objects.filter(tags__in=[tag])

        paginator = Paginator(post_objects, 10)
        page = request.GET.get("page")
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        
        context = {
            "posts": posts,
            "page": page,
            "tag": tag,
        }

        return render(request, "blog/post/list.html", context=context)


class PostDetailView(View):
    """
        Handles everthing that's related to post-detail views.
    """
    def get(self, request, post):
        post = get_object_or_404(Post, status="published", slug=post)
        comments = post.comments.filter(active=True)
        comment_form = CommentForm()

        # get similar posts
        tag_ids = post.tags.values_list("id", flat=True)
        similar_posts = Post.objects.filter(
            status="published",
            tags__in=tag_ids,
        ).exclude(id=post.id).annotate(same_tags_num=Count("tags")).order_by("-same_tags_num", "-publish")[0:4]
        
        context = {
            "post": post,
            "comments": comments,
            "new_comment": False,
            "comment_form": comment_form,
            "similar_posts": similar_posts,
        }
        return render(request, "blog/post/detail.html", context=context)
    
    def post(self, request, post):
        post = get_object_or_404(Post, status="published", slug=post)
        comments = post.comments.filter(active=True)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
        else:
            pass
        
        context = {
            "post": post,
            "comments": comments,
            "new_comment": new_comment,
            "comment_form": comment_form,
        }
        return render(request, "blog/post/detail.html", context=context)

blog/templates/blog/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'css/blog.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            {% block content %}
            <!-- The real content goes HERE! -->
            {% endblock %}
        </div>
    </body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% load md_extras %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
<h2><a href="/">&laquo;</a></h2>
<h1><a href="./">{{ post.title }}</a><h1>
<p style="font-size: 14px;">
    Tags: 
    {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_&_tag' tag.slug %}">{{ tag.name }}{% if not forloop.last %}, {% endif %}</a>
    {% endfor %}
</p>
<p class="date">Published on {{ post.publish }} by {{ post.author }}</p>

<div id="postbody" style="font-family: sans-serif;">
    {{ post.body | markdown | safe | linebreaks }}
</div>

<h3>Similar Posts</h3>
{% for post in similar_posts %}
    <p><a href="{% url 'blog:post_detail' post.slug %}">{{ post.title }}</a></p>
{% empty %}
    <p>There are no similar posts... yet.</p>
{% endfor %}

{% with comments.count as total_comments %}
    <h3>
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h3>
{% endwith %}

{% if new_comment %}
    <h3>Your comment has been added!</h3>
{% else %}
    <h5>Add a new comment</h5>
    <form method="post"> {% csrf_token %}
        {{ comment_form.as_p }}
        <button type="submit">Add comment</button>
    </form>
{% endif %}

{% for comment in comments %}
    <div class="comment">
        <p class="info">
            {{ comment.name }} <br>
            {{ comment.created }}
        </p>
        {{ comment.body | linebreaks }}
    </div>
{% empty %}
    <p>There are no comments... yet.</p>
{% endfor %}

{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% load md_extras %}

{% block title %} bichanna {% endblock %}

{% block content %}

<h1><a href="/">bichanna's Blog (?)</a></h1>
{% if tag %}
    <h3>Posts tagged with <code>"{{ tag.name }}"</code></h3>
{% endif %}
{% for post in posts %}
    <h2><a href="{% url 'blog:post_detail' post.slug %}">{{ post.title }}</a></h2>
    <p class="tags" style="font-size: 14px;">
        Tags: 
        {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_&_tag' tag.slug %}">{{ tag.name }}{% if not forloop.last %}, {% endif %}</a>
        {% endfor %}
    </p>
    <p class="date">Published on {{ post.publish }} by {{ post.author }}</p>
    <div>
        {{ post.body | markdown | safe | truncatewords:10 | linebreaks }}
    </div>
{% endfor %}
{% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            {{ page.number }}/{{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>